### ISSUE TITLE
最新node.js不兼容

### ISSUE THREAD

**Issue by haoeixc** [TimeRainStarSky/TRSS_Script#11]
- TRSS-Yunzai 下载完成，用时：36.445秒

- 正在使用 pnpm 安装 依赖

/usr/lib/node_modules/pnpm/dist/pnpm.cjs:142652
        value[symToStringTag] = void 0;
                              ^

TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<WeakMap>'
    at getRawTag (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:142652:31)
    at baseGetTag (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:142695:66)
    at ../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_getTag.js (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:143851:230)
    at __require (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)
    at ../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_baseIsEqualDeep.js (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:143882:18)
    at __require (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)
    at ../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_baseIsEqual.js (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:143929:27)
    at __require (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)
    at ../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isEqual.js (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:143947:23)
    at __require (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)

Node.js v22.0.0

! 依赖 安装失败，用时：2.298秒

**Comment by TimeRainStarSky** [comment]
```sh
tsab c pacman -Syu nodejs-lts-iron
y
```
